# MinePin Config
# 配置优先级： 环境变量 > 配置文件内容(./conf/config.yaml)
# debug 模式下 *.debug > *
runmode: release             # MINEPIN_RUNMODE 开发模式, debug, release, test
port: 6000                   # MINEPIN_PORT HTTP绑定端口
port_debug: 6001             # MINEPIN_PORT_DEBUG
name: minepin                # MINEPIN_NAME API Server 服务名称
max_ping_count: 10           # MINEPIN_MAX_PING_COUNT 服务健康监测最多尝试次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
                             # MINEPIN_JWT_SECRET JWT 签发密钥，该值为测试密钥
log:
  level: debug        # MINEPIN_LOG_LEVEL debug->info->warn->error
  file_name: log/minepin-backend.log
                      # MINEPIN_LOG_FILE_NAME debug file path
  max_size_mb: 1      # MINEPIN_LOG_MAX_SIZE_MB
  max_file_num: 64    # MINEPIN_LOG_MAX_FILE_NUM
  max_file_day: 7     # MINEPIN_LOG_MAX_FILE_DAY
  compress: false     # MINEPIN_LOG_COMPRESS 日志压缩
  stdout: true        # MINEPIN_LOG_STDOUT 显式指定日志输出到 stdout
  only_stdout: true   # MINEPIN_LOG_ONLY_STDOUT 日志仅输出到 stdout
db:
  type: sqlite           # MINEPIN_DB_TYPE mysql or sqlite
  addr: ./minepin.db     # MINEPIN_DB_ADDR example for sqlite
  name: MYSQL_NAME       # MINEPIN_DB_NAME
  username: USERNAME     # MINEPIN_DB_USERNAME
  password: PASSWORD     # MINEPIN_DB_PASSWORD
  type_debug: mysql                     # MINEPIN_DB_TYPE_DEBUG
  name_debug: MYSQL_NAME                # MINEPIN_DB_NAME_DEBUG
  addr_debug: xxxx.xxxx.xxxx.xxxx:3306  # MINEPIN_DB_ADDR_DEBUG
  username_debug: USERNAME              # MINEPIN_DB_USERNAME_DEBUG
  password_debug: PASSWORD              # MINEPIN_DB_PASSWORD_DEBUG

# 注： _debug 后缀表示runmode 为 debug 时生效配置